import type { ExpoConfig } from 'expo/config';

/**
 * Expo app configuration.
 *
 * Two widget plugins, because there is no cross-platform widget layer (research R2):
 * `expo-widgets` compiles SwiftUI views for iOS, `react-native-android-widget` produces
 * RemoteViews for Android. Both are configured here so the shared-storage keys in
 * `contracts/widget-payload.md` are declared in exactly one place.
 *
 * **Expo Go will not work.** `expo-widgets` is unavailable in Expo Go, so widget work requires a
 * development build: `expo run:ios` / `expo run:android` rather than `expo start`. Simulator and
 * emulator testing is unaffected (SC-012).
 */

const BUNDLE_ID = 'app.goeat.client';

/** The App Group MUST match `PAYLOAD_STORAGE.ios` in @go-eat/contract-types. */
const IOS_APP_GROUP = `group.${BUNDLE_ID}`;

/** The SharedPreferences file MUST match `PAYLOAD_STORAGE.android`. */
const ANDROID_PREFERENCES = 'goeat_widget';

const config: ExpoConfig = {
  name: 'Go-Eat',
  slug: 'go-eat',
  version: '0.1.0',
  scheme: 'goeat',
  orientation: 'portrait',
  userInterfaceStyle: 'automatic',
  // New Architecture is on by default from SDK 57+; there is no longer a config field for it.

  ios: {
    bundleIdentifier: BUNDLE_ID,
    supportsTablet: false,
    // iOS 17+ is required for App Intent–driven widget refresh, which is what lets the refresh
    // button advance the cursor without launching the app (FR-005).
    deploymentTarget: '17.0',
    entitlements: {
      'com.apple.security.application-groups': [IOS_APP_GROUP],
    },
    infoPlist: {
      NSLocationWhenInUseUsageDescription:
        'Go-Eat uses your location once per suggestion to find a restaurant near you. It is not stored or shared.',
    },
  },

  android: {
    package: BUNDLE_ID,
    permissions: ['ACCESS_COARSE_LOCATION', 'ACCESS_FINE_LOCATION'],
  },

  plugins: [
    'expo-router',
    'expo-location',

    [
      'expo-widgets',
      {
        // Render-only SwiftUI views. Any logic appearing here is a design failure — it would then
        // have to be written and tested twice, once more in Kotlin.
        widgetsDir: './widgets/ios',
        appGroup: IOS_APP_GROUP,
        // Generated by `npm run tokens:generate`. Never hand-edited (Constitution VI.1).
        xcassets: './generated/ios/Colors.xcassets',
      },
    ],

    [
      'react-native-android-widget',
      {
        widgets: [
          {
            name: 'GoEat',
            label: 'Go-Eat',
            minWidth: '180dp',
            minHeight: '110dp',
            resizeMode: 'horizontal|vertical',
            // 30 minutes, matching batchTrustSeconds (1800s). A shorter period would wake the
            // widget more often than the data it renders can change.
            updatePeriodMillis: 1_800_000,
            description: 'One restaurant. No list.',
          },
        ],
        preferencesName: ANDROID_PREFERENCES,
        // Generated colors.xml + values-night/colors.xml (ADR-001: fixed palette, no system_*).
        resourcesDir: './generated/android/res',
      },
    ],
  ],

  extra: {
    apiUrl: process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3000',
  },
};

export default config;
export { ANDROID_PREFERENCES, BUNDLE_ID, IOS_APP_GROUP };
