/**
 * Types for the Go-Eat suggestion API, generated by hand from
 * `specs/001-widget-restaurant-suggestion/contracts/suggestion-api.yaml`.
 *
 * The YAML is the source of truth. If the two disagree, the YAML wins and this file is the bug.
 */

/**
 * Dietary tags. The same vocabulary serves two different mechanisms:
 * `exclusions` are hard filters (FR-011), `preferences` are positive scoring inputs. A tag may
 * appear in one or the other, never both — see `CycleRequest`.
 */
export const DIETARY_TAGS = [
  'vegetarian',
  'vegan',
  'halal',
  'kosher',
  'gluten_free',
  'dairy_free',
  'nut_free',
  'shellfish_free',
  'pescatarian',
] as const;

export type DietaryTag = (typeof DIETARY_TAGS)[number];

export type UnitSystem = 'metric' | 'imperial';

/**
 * Why the batch looks the way it does.
 *
 * `no_results` and `all_filtered` are deliberately distinct. "Nothing good here" and "your filters
 * removed everything" call for different user actions, and collapsing them would strand a user who
 * could fix the problem in preferences.
 */
export type BatchState = 'suggestion' | 'no_results' | 'all_filtered';

export interface LocationAnchor {
  lat: number;
  lng: number;
  /** ISO 8601. Drives staleness. */
  capturedAt: string;
}

export interface CycleRequest {
  /** -90..90 */
  lat: number;
  /** -180..180 */
  lng: number;
  /**
   * Random per-install identifier used ONLY for rate limiting. Not an account, not a user
   * identity, never joined to location in any store, regenerated on reinstall (FR-032).
   */
  installationId: string;
  /** Determines `distanceLabel` formatting. Widgets cannot convert units. */
  unitSystem: UnitSystem;
  /** Hard filters. Matching venues are removed before scoring (FR-011). */
  exclusions?: DietaryTag[];
  /** Positive scoring inputs. MUST NOT overlap `exclusions`. */
  preferences?: DietaryTag[];
  /**
   * Optional. Supply to reproduce a previous cycle's ordering exactly (FR-022b, SC-014).
   * Omitted in production; used by tests and the golden-fixture suite.
   */
  seed?: string;
}

/**
 * One render-ready restaurant.
 *
 * Every field is a finished string. The widget performs no formatting, rounding, unit conversion,
 * or URL construction — it cannot, because widgets do not run JavaScript (research R1/R2).
 *
 * Note what is absent: no score, no rank, no count of siblings, no reference to the next item.
 * Withholding that data makes a comparison UI unbuildable rather than merely discouraged
 * (FR-001, Principle II).
 */
export interface SuggestionItem {
  providerPlaceId: string;
  /** Pre-truncated to the widget display budget (≤ 60). */
  name: string;
  /** Human-readable, derived from provider types. Never a raw enum. ≤ 30. */
  cuisineLabel: string;
  /** e.g. `"4.6"` */
  ratingLabel: string;
  /** Pre-formatted and abbreviated, e.g. `"1.2k"` */
  reviewCountLabel: string;
  /** Pre-formatted in the requested unit system, e.g. `"0.4 mi"` */
  distanceLabel: string;
  /** Primary deep link to the provider listing page (FR-023). */
  listingUrl: string;
  /** Used when the primary link fails to resolve (FR-025). */
  fallbackUrl: string;
}

export interface CycleResponse {
  cycleId: string;
  /** The seed actually used. Always returned, so any cycle is reproducible (FR-022b). */
  seed: string;
  issuedAt: string;
  anchor: LocationAnchor;
  /**
   * Ordered and render-ready, at most 5. The client MUST NOT reorder — ordering is a backend
   * concern and client-side sorting would break FR-013 reproducibility.
   */
  items: SuggestionItem[];
  /** Mirrors backend config (FR-019). When false the client hides refresh and never advances. */
  refreshEnabled: boolean;
  state: BatchState;
}

/**
 * Client-relevant configuration.
 *
 * Scoring weights are deliberately absent. They are operator-owned and never user-visible
 * (Principle II), and `services/suggestion-api/__tests__/config.contract.test.ts` asserts they
 * never leak into this shape.
 */
export interface ClientConfig {
  refreshEnabled: boolean;
  /** 1..5 */
  batchSize: number;
  /**
   * Drift beyond this invalidates the active batch (FR-021). This value is what "changed
   * materially enough" in FR-021 resolves to. Rationale in research R12.
   */
  locationDriftThresholdMeters: number;
  /** Anchor older than this is stale; the widget renders the stale state. */
  anchorFreshnessSeconds: number;
  /**
   * After this, open/closed data is no longer trusted and the batch is invalidated (FR-021),
   * preventing a closed venue being shown as open. MUST remain greater than
   * `anchorFreshnessSeconds` so the anchor goes stale before the batch expires.
   */
  batchTrustSeconds: number;
}

export type ErrorCode = 'bad_request' | 'rate_limited' | 'provider_unavailable' | 'internal';

export interface ApiError {
  code: ErrorCode;
  /** Diagnostic text for developers. NEVER rendered in the widget. */
  message: string;
}

export interface HealthResponse {
  status: 'ok';
}
